DROP TABLE IF EXISTS Topics_In_Forum;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS Posts_In_Topic;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
username VARCHAR(10) NOT NULL UNIQUE,
stuId VARCHAR(10) NULL
);

CREATE TABLE Post (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
text VARCHAR(800) NOT NULL,
postedAT VARCHAR(100) NOT NULL
);

CREATE TABLE Topic (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
postedAT VARCHAR(100) NOT NULL
);

CREATE TABLE Posts_In_Topic ( 
id INTEGER PRIMARY KEY AUTO_INCREMENT,
topicid INTEGER, 
postid INTEGER, 
FOREIGN KEY (topicid) REFERENCES Topic(id), 
FOREIGN KEY (postid) REFERENCES Post(id)
);

CREATE TABLE Forum (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Topics_In_Forum ( 
id INTEGER PRIMARY KEY AUTO_INCREMENT, 
topicid INTEGER, 
forumid INTEGER, 
FOREIGN KEY (topicid) REFERENCES Topic(id), 
FOREIGN KEY (forumid) REFERENCES Forum(id)
);
